### ISSUE TITLE
Inverted colors for number of added/deleted lines.

### ISSUE THREAD

**Issue by maxfrei750** [facelessuser/merge-dracula-theme#7]
First of all: Thanks for your awesome work!

I have a question: When I apply your theme (and also in the official screenshot) removed lines themselves are red and added lines are green (as I would expect it), but the _numbers_ of removed/added lines are exactly the other way round:

<img width="619" alt="image" src="https://user-images.githubusercontent.com/36265931/150941851-c6f46ac9-01b2-4d2f-b9ca-d8b7477b7cb2.png">

 Is this intended?

Just to make sure that I'm not misunderstanding Sublime Merge's design, I checked the default theme, and there the colors match.

**Comment by facelessuser** [comment]
Fix has been tagged in 2.1.1
